[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dooms"
version = "1.1.0"
authors = [
  { name="DOOMS Team", email="team@dooms.lang" },
]
description = "A custom strictly-typed dynamic scripting language"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
dooms = "dooms.cli:main"

[tool.setuptools.packages.find]
include = ["dooms*"]
